### ISSUE TITLE
Project wont run

### ISSUE THREAD

**Issue by Alex61NN5** [contentful-labs/product-catalogue-web.ts#3]
Just tried to start the project for the first time, project wont run, I have run `npm install`  and on `npm start` you get these errors
    
    ERROR in C:/test-projects/product-catalogue-web.ts/src/app/app.module.ts (6,10): Module '"C:/test-projects/product-catalogue-web.ts/node_modules/@angular/material/material"' has no exported member 'MdListModule'.

    ERROR in C:/test-projects/product-catalogue-web.ts/src/app/app.module.ts (6,24): Module '"C:/test-projects/product-catalogue-web.ts/node_modules/@angular/material/material"' has no exported member 'MdInputModule'.

    ERROR in C:/test-projects/product-catalogue-web.ts/src/app/app.module.ts (6,39): Module '"C:/test-projects/product-catalogue-web.ts/node_modules/@angular/material/material"' has no exported member 'MdToolbarModule'.

    ERROR in C:/test-projects/product-catalogue-web.ts/src/app/app.module.ts (6,56): Module '"C:/test-projects/product-catalogue-web.ts/node_modules/@angular/material/material"' has no exported member 'MdButtonModule'.

    ERROR in C:/test-projects/product-catalogue-web.ts/src/app/app.module.ts (6,72): Module '"C:/test-projects/product-catalogue-web.ts/node_modules/@angular/material/material"' has no exported member 'MdCardModule'.

    ERROR in C:/test-projects/product-catalogue-web.ts/src/app/app.module.ts (6,86): Module '"C:/test-projects/product-catalogue-web.ts/node_modules/@angular/material/material"' has no exported member 'MdTabsModule'.

    ERROR in MdListModule is not an NgModule

    ERROR in C:/test-projects/product-catalogue-web.ts/src/app/app.module.ts (6,10): Module '"C:/test-projects/product-catalogue-web.ts/node_modules/@angular/material/material"' has no exported member 'MdListModule'.

    ERROR in C:/test-projects/product-catalogue-web.ts/src/app/app.module.ts (6,24): Module '"C:/test-projects/product-catalogue-web.ts/node_modules/@angular/material/material"' has no exported member 'MdInputModule'.

    ERROR in C:/test-projects/product-catalogue-web.ts/src/app/app.module.ts (6,39): Module '"C:/test-projects/product-catalogue-web.ts/node_modules/@angular/material/material"' has no exported member 'MdToolbarModule'.

    ERROR in C:/test-projects/product-catalogue-web.ts/src/app/app.module.ts (6,56): Module '"C:/test-projects/product-catalogue-web.ts/node_modules/@angular/material/material"' has no exported member 'MdButtonModule'.

    ERROR in C:/test-projects/product-catalogue-web.ts/src/app/app.module.ts (6,72): Module '"C:/test-projects/product-catalogue-web.ts/node_modules/@angular/material/material"' has no exported member 'MdCardModule'.

    ERROR in C:/test-projects/product-catalogue-web.ts/src/app/app.module.ts (6,86): Module '"C:/test-projects/product-catalogue-web.ts/node_modules/@angular/material/material"' has no exported member 'MdTabsModule'.  

**Running Angular**

    @angular/cli: 1.2.3
    node: 9.2.1
    os: win32 x64
    @angular/animations: 4.4.6
    @angular/cdk: 2.0.0-beta.12
    @angular/common: 4.4.6
    @angular/compiler: 4.4.6
    @angular/core: 4.4.6
    @angular/forms: 4.4.6
    @angular/http: 4.4.6
    @angular/material: 2.0.0-beta.12
    @angular/platform-browser: 4.4.6
    @angular/platform-browser-dynamic: 4.4.6
    @angular/router: 4.4.6
    @angular/cli: 1.2.3
    @angular/compiler-cli: 4.4.6
    @angular/language-service: 4.4.6

Thanks

**Comment by stefanjudis** [comment]
Hmm... this project doesn't serve a lockfile (yet). I assume this come from some updated dependency. I'll have a look asap. :)

**Comment by stefanjudis** [comment]
@Alex61NN5 

Fix is on its way (#4). ;)

**Comment by stefanjudis** [comment]
@Alex61NN5 should be resolved now. :)

**Comment by Alex61NN5** [comment]
Great! thankyou!
